spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fikadb
    username: fikauser
    password: fikapassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    com.wefly.fika: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace